--This file is automatically generated by generate_VHDL_file.m, 08-Nov-2021

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package CONFIG is
	type INPUT is array (natural range <>) of integer range 0 to 255;
	signal connection : INPUT (11 downto 0);
	--connection 2 downto 0 is the input of the neural network
	--connection 11 downto 10 is the output of the neural network

	-- int Arrays with Constants
	type constIntArray is ARRAY (natural range <>) of integer;
	constant networkStructure : constIntArray (2 downto 0) := (2,7,3);
	constant connnectionRange : constIntArray (3 downto 0) := (12,10,3,0);
	constant weights : constIntArray (43 downto 0) := (3250,-82,80,-69,174,-150,33,-58,3562,58,-160,61,-94,76,-96,14,48671,291,79,-45,18012,-344,72,310,-9271,133,-42,-176,-5929,-357,-24,374,939,361,47,-265,21193,-206,48,191,12835,99,7,-71);

	--mapping the 2D network to the 1D Array with the weights
	type KOORDINATES is array (0 to 7, 1 to 2) of natural;
	constant positions: KOORDINATES:=( 
				(0,28),
				(4,36),
				(8,44),
				(12,0),
				(16,0),
				(20,0),
				(24,0),
				(28,0));

	-- Ranges for the sum inside a neuron and the multiplication of an input signal with a weight
	constant maxSumRange: integer:=262143;
	constant minSumRange: integer:=-262144;
	constant maxMultRange: integer:=131071;
	constant minMultRange: integer:=-131072;

	-- -- Array for all multiplication results inside a neuron
	type multResults is ARRAY (natural range <>) of integer range minMultRange to maxMultRange;
end CONFIG;
